definitions:
  dto.CreateAccountReq:
    properties:
      password:
        description: 密码
        minLength: 6
        type: string
      username:
        description: 用户名
        maxLength: 30
        minLength: 2
        type: string
    required:
    - password
    - username
    type: object
  dto.CreateAccountResp:
    properties:
      code:
        description: 状态码
        type: integer
      message:
        description: 消息
        type: string
    type: object
info:
  contact: {}
paths:
  /account/create:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateAccountResp'
      summary: 创建账号
      tags:
      - account
swagger: "2.0"
