definitions:
  dto.Auth:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.CreateAccountReq:
    properties:
      password:
        minLength: 6
        type: string
      username:
        maxLength: 30
        minLength: 2
        type: string
    required:
    - password
    - username
    type: object
  dto.UpdateAccountReq:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role_id:
        type: integer
      show_name:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /account/create:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 创建账号
      tags:
      - account
  /account/delete:
    get:
      consumes:
      - application/json
      description: delete account
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 删除账号
      tags:
      - account
  /account/list:
    get:
      consumes:
      - application/json
      description: get account list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      - description: name
        in: query
        name: name
        type: string
      - description: status
        in: query
        name: status
        type: integer
      - description: roleID
        in: query
        name: roleID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 获取账号列表
      tags:
      - account
  /account/update:
    post:
      consumes:
      - application/json
      description: update account
      parameters:
      - description: account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateAccountReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 更新账号
      tags:
      - account
  /auth:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: req
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 登录
      tags:
      - auth
swagger: "2.0"
